"""adding tenant_id

Revision ID: 333f5589c8a8
Revises: efe911839fdc
Create Date: 2025-04-13 19:16:22.964848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333f5589c8a8'
down_revision: Union[str, None] = 'efe911839fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_tenants_tenant_id'), 'tenants', ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tenants_tenant_id'), 'tenants', type_='unique')
    op.drop_column('tenants', 'tenant_id')
    # ### end Alembic commands ###
