"""adjusting_tenant_relationship

Revision ID: 3b403b6760e4
Revises: 7baf1c6bd9fa
Create Date: 2025-04-14 08:31:30.643109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b403b6760e4'
down_revision: Union[str, None] = '7baf1c6bd9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tenants', 'usage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'usage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tenants', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
