"""redefining relationships

Revision ID: 7baf1c6bd9fa
Revises: 333f5589c8a8
Create Date: 2025-04-13 20:19:56.961303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baf1c6bd9fa'
down_revision: Union[str, None] = '333f5589c8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sku_enum = sa.Enum('MEMORY', 'CPU', 'STORAGE', name='sku_enum')
    sku_enum.create(op.get_bind())  # Create the ENUM type in the database
    op.add_column('contracts', sa.Column('sku', sku_enum, nullable=False))
    op.add_column('contracts', sa.Column('rate', sa.Float(), nullable=False))
    op.add_column('contracts', sa.Column('unit', sa.String(), nullable=False))
    op.add_column('contracts', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('contracts', sa.Column('effective_date', sa.DateTime(), nullable=False))
    op.add_column('contracts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('fk_contracts_usage_id_usage', 'contracts', type_='foreignkey')
    op.drop_constraint('fk_contracts_tenant_id_tenants', 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'tenant_id')
    op.drop_column('contracts', 'name')
    op.drop_column('contracts', 'usage_id')
    op.add_column('tenants', sa.Column('email', sa.String(), nullable=False))
    op.add_column('tenants', sa.Column('usage_id', sa.Integer(), nullable=False))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('fk_tenants_contract_id_usage', 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenants_contract_id_contracts'), 'tenants', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(op.f('fk_tenants_usage_id_usage'), 'tenants', 'usage', ['usage_id'], ['id'])
    op.drop_column('tenants', 'name')
    op.add_column('usage', sa.Column('total_usage', sa.Float(), nullable=False))
    op.add_column('usage', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('usage', sa.Column('invoice_value', sa.Float(), nullable=False))
    op.add_column('usage', sa.Column('paid', sa.Boolean(), nullable=False))
    op.add_column('usage', sa.Column('info', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('usage', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('usage', 'tenant')
    op.drop_column('usage', 'resource_name')
    op.drop_column('usage', 'value')
    op.drop_column('usage', 'resource_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('resource_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usage', 'updated_at')
    op.drop_column('usage', 'created_at')
    op.drop_column('usage', 'info')
    op.drop_column('usage', 'paid')
    op.drop_column('usage', 'invoice_value')
    op.drop_column('usage', 'total_amount')
    op.drop_column('usage', 'total_usage')
    op.add_column('tenants', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_tenants_usage_id_usage'), 'tenants', type_='foreignkey')
    op.drop_constraint(op.f('fk_tenants_contract_id_contracts'), 'tenants', type_='foreignkey')
    op.create_foreign_key('fk_tenants_contract_id_usage', 'tenants', 'usage', ['contract_id'], ['id'])
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'usage_id')
    op.drop_column('tenants', 'email')
    op.add_column('contracts', sa.Column('usage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_contracts_tenant_id_tenants', 'contracts', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('fk_contracts_usage_id_usage', 'contracts', 'usage', ['usage_id'], ['id'])
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'effective_date')
    op.drop_column('contracts', 'price')
    op.drop_column('contracts', 'unit')
    op.drop_column('contracts', 'rate')
    op.drop_column('contracts', 'sku')
    sku_enum = sa.Enum('MEMORY', 'CPU', 'STORAGE', name='sku_enum')
    sku_enum.drop(op.get_bind()) # drop the enum created
    # ### end Alembic commands ###
